### ISSUE TITLE
Please Make This For Fragments!!

### ISSUE THREAD

**Issue by MikeRzDev** [wunderlist/android-sliding-layer-lib#54]
Hi, im very pleased with this, but when you are going to use it in a fragment, the SlindingLayer overlaps with the fragment widgets, so please make it available to be compatible with tab navigation :).

**Comment by andresvillenas** [comment]
Mike, you should try instantiating the Fragment and then use fragmentmanager to replace the fragment in any container inside the SlidingLayer

<com.wunderlist.slidinglayer.SlidingLayer
            android:id="@+id/slidingLayer1"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_above="@+id/audio_player_fragment"
            slidingLayer:stickTo="bottom">

            <FrameLayout
                android:id="@+id/course_flow_container"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical"
                android:weightSum="1">

            </FrameLayout>

        </com.wunderlist.slidinglayer.SlidingLayer>
