### ISSUE TITLE
Upload .aar to Maven Central

### ISSUE THREAD

**Issue by fhur** [wunderlist/android-sliding-layer-lib#55]
It would be cool if you could just 
```gradle
compile 'com.wunderkinder:android-sliding-layer-lib:1.0@aar'
```
i.e. if .aar was uploaded to maven central

**Comment by jitpack-io** [comment]
Btw, it's already easy to get it as a dependency from https://jitpack.io/#wunderlist/android-sliding-layer-lib/8dabb7728e
Would also be nice if there as a GitHub release
