### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by crysan** [wunderlist/android-sliding-layer-lib#62]
Please set dependencies;
Ty!

**Comment by umarmansuri** [comment]
Click on the Right click of AppName and go to Mode Setting >  then click on Project Name and on Right side panel you see dependencies click on that you will see bottom panel with plus(+) and minus (-) sign click (+) and add dependencies in Latest Verion of Android Studio

**Comment by crysan** [comment]
Ok!
