### ISSUE TITLE
middle Not Recognized As Valid stickTo Option

### ISSUE THREAD

**Issue by commonsguy** [wunderlist/android-sliding-layer-lib#75]
The `stickTo` attribute is documented as supporting `middle`. However, that is not accepted:

    Error:(15, 27) String types not allowed (at 'stickTo' with value 'middle').

Values of `right` and `bottom` are. `middle` does not seem to be in your `stickTo` `attr` `enum`.

The documentation also mentions an `auto` value, which does not appear in the `enum` either.

**Comment by JlUgia** [comment]
Hello @commonsguy! Thanks for looking into this. The values 'middle' and 'auto' got discarded as they added almost no value and a lot of noise to the rest of the functionality. As you correctly point these are not valid anymore. The [following PR](https://github.com/wunderlist/android-sliding-layer-lib/compare/jose/remove_wrong_values_from_docs) addresses that.

/cc @aconsuegra @CesarValiente
