### ISSUE TITLE
Import in Eclipse

### ISSUE THREAD

**Issue by libathos** [wunderlist/android-sliding-layer-lib#87]
Hello, I've been trying to import this project in eclipse and I can't figure out how. I had imported over a year ago but that wasn't the gradle build. How can I import it now?

**Comment by CesarValiente** [comment]
Hi @libathos it should be easy to import this library in Eclipse, just adding the library folder, or using the Eclipse Gradle Plugin to allow you import the library from mavencentral or jcenter.

And btw, may I ask, why don't you use Android Studio? It has amazing cool features that boost your development, most of all Android developers use it, and most important, the Android Development Toolkit (ADT) that you need to develop Android in Eclipse is not maintained anymore by Google (http://android-developers.blogspot.de/2015/06/an-update-on-eclipse-android-developer.html).

So yeah, you should give Android Studio a try ;-)

Cheers mate.
