### ISSUE TITLE
Close layer on tap outside

### ISSUE THREAD

**Issue by shashank090789** [wunderlist/android-sliding-layer-lib#97]
how to close the layer if tap outside.

**Comment by jmoscatiello** [comment]
<View
        android:id="@+id/mask"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/translucent_black"
        android:visibility="gone"/>

Add a view underneath that only shows when opened. Then add an on click on that view

**Comment by shashank090789** [comment]
thanks
